

-- Remove MQT refresh task, procedure and associated tables
CALL SYSPROC.ADMIN_TASK_REMOVE (
  'REFRESH MQTS EVERY 60S', 
  NULL
)@

DROP PROCEDURE REFRESH_MQTS@

DROP TABLE MQT_REFRESH_TIME@

-- DROP last 30 day MQTS

DROP TABLE NOISE_REDUCTION_LAST_30_DAYS@

DROP TABLE INCIDENT_HANDLING_METRICS_LAST_30_DAYS@

DROP TABLE INCIDENT_ACTIVTY_BY_TIME_LAST_30_DAYS@

DROP TABLE INCIDENT_ACTIVTY_BY_PRIORITY_LAST_30_DAYS@

-- DROP last 30 day views
DROP VIEW NOISE_REDUCTION_LAST_30_DAYS_VW@

DROP VIEW INCIDENT_HANDLING_METRICS_LAST_30_DAYS_VW@

DROP VIEW INCIDENT_ACTIVTY_BY_TIME_LAST_30_DAYS_VW@

DROP VIEW INCIDENT_ACTIVTY_BY_PRIORITY_LAST_30_DAYS_VW@

DROP VIEW INCIDENTS_BY_RESOURCE_GROUP_SCOPE_CHANGED_IN_LAST_30_DAYS@

-- DROP last 7 day MQTS
DROP TABLE NOISE_REDUCTION_LAST_7_DAYS@

DROP TABLE INCIDENT_HANDLING_METRICS_LAST_7_DAYS@

DROP TABLE INCIDENT_ACTIVTY_BY_TIME_LAST_7_DAYS@

DROP TABLE INCIDENT_ACTIVTY_BY_PRIORITY_LAST_7_DAYS@


-- DROP last 7 day views
DROP VIEW NOISE_REDUCTION_LAST_7_DAYS_VW@

DROP VIEW INCIDENT_HANDLING_METRICS_LAST_7_DAYS_VW@

DROP VIEW INCIDENT_ACTIVTY_BY_TIME_LAST_7_DAYS_VW@

DROP VIEW INCIDENT_ACTIVTY_BY_PRIORITY_LAST_7_DAYS_VW@

DROP VIEW INCIDENTS_BY_RESOURCE_GROUP_SCOPE_CHANGED_IN_LAST_7_DAYS@

-- DROP last 24 day MQTS
DROP TABLE NOISE_REDUCTION_LAST_24_HOURS@

DROP TABLE INCIDENT_HANDLING_METRICS_LAST_24_HOURS@

DROP TABLE INCIDENT_ACTIVTY_BY_TIME_LAST_24_HOURS@

DROP TABLE INCIDENT_ACTIVTY_BY_PRIORITY_LAST_24_HOURS@

-- DROP last 24 hour views
DROP VIEW NOISE_REDUCTION_LAST_24_HOURS_VW@

DROP VIEW INCIDENT_HANDLING_METRICS_LAST_24_HOURS_VW@

DROP VIEW INCIDENT_ACTIVTY_BY_TIME_LAST_24_HOURS_VW@

DROP VIEW INCIDENT_ACTIVTY_BY_PRIORITY_LAST_24_HOURS_VW@

DROP VIEW INCIDENTS_BY_RESOURCE_GROUP_SCOPE_CHANGED_IN_LAST_24_HOURS@


-- DROP base views
DROP VIEW INCIDENTS_BY_RESOURCE_GROUP_SCOPE@

DROP VIEW INCIDENT_ALERT_RESOURCE_GROUP_IDS@


-- DROP triggers
DROP TRIGGER UPDATE_INCIDENTS_TO_ALERTS_TRIGGER@

DROP TRIGGER UPDATE_ALERTS_TO_RESOURCE_GROUPS_TRIGGER@

DROP TRIGGER CREATE_INCIDENTS_TO_ALERTS_TRIGGER@

DROP TRIGGER CREATE_ALERTS_TO_RESOURCE_GROUPS_TRIGGER@


-- DROP procedures

DROP PROCEDURE ALERTS_RELATIONS_UPDATE@

DROP PROCEDURE PROCESS_ALERT_RESOURCE_GROUP@

DROP PROCEDURE INCIDENTS_RELATIONS_UPDATE@


-- DROP tables

DROP TABLE INCIDENTS_ALERTS_RELATIONS@

DROP TABLE ALERTS_RESOURCE_GROUPS_RELATIONS@

DROP TABLE RESOURCE_GROUP_ENTITYTYPES@

DROP TABLE RESOURCE_GROUP_TAGS@

DROP TABLE RESOURCE_GROUP_SCOPES@

DROP TABLE RESOURCE_GROUPS@

DROP TABLE PAST_DAYS@

DROP TABLE PAST_HOURS@

DROP TABLE INCIDENT_PRIORITY_TYPES@

-- DROP column alterations

ALTER TABLE ALERTS_REPORTER_STATUS DROP COLUMN RESOURCEGROUPDETAILS@

ALTER TABLE ALERTS_REPORTER_STATUS DROP COLUMN RESOURCEGROUPIDS@

ALTER TABLE INCIDENTS_REPORTER_STATUS DROP COLUMN ALERTIDS@

COMMIT WORK@

